/*----------------------------------------------------------
MASV: N17DCAT055
HO TEN: DO ANH QUAN
LAB: 04
NGAY: 27/9/2020
----------------------------------------------------------*/ 
CREATE DATABASE QLSV_CANHAN
USE QLSV_CANHAN
CREATE TABLE SINHVIEN(
	MASV NVARCHAR(20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(100) ,
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(MAX) NOT NULL
)
CREATE TABLE NHANVIEN(
	MANV VARCHAR(20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY(MAX),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(MAX) NOT NULL
)
CREATE TABLE LOP(
	MALOP VARCHAR(20) PRIMARY KEY,
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20)
)
 --CAU LENH TAO STORED PROCEDURE 
CREATE PROC SP_INS_ENCRYPT_SINHVIEN 
	@MASV NVARCHAR(20),
	@HOTEN NVARCHAR(100),
	@NGAYSINH DATETIME,
	@DIACHI NVARCHAR(200),
	@MALOP NVARCHAR(20),
	@TENDN NVARCHAR(100),
	@MATKHAU NVARCHAR(MAX)
AS
	INSERT INTO SINHVIEN(MASV, HOTEN, NGAYSINH, DIACHI, MALOP, TENDN, MATKHAU) VALUES(@MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, CAST(@MATKHAU AS varbinary))
CREATE PROC SP_INS_ENCRYPT_NHANVIEN 
	@MANV NVARCHAR(20) ,
	@HOTEN NVARCHAR(100),
	@EMAIL VARCHAR(20),
	@LUONG VARCHAR(MAX),
	@TENDN NVARCHAR(100),
	@MATKHAU VARCHAR(MAX)
AS
	INSERT INTO NHANVIEN(MANV, HOTEN, EMAIL, LUONG, TENDN, MATKHAU) VALUES(@MANV, @HOTEN, @EMAIL, CAST(@LUONG AS varbinary(MAX)), @TENDN, CAST(@MATKHAU AS varbinary(MAX)))
	drop proc SP_SEL_ENCRYPT_NHANVIEN
	EXEC SP_INS_ENCRYPT_NHANVIEN 'NV10', 'NHAN VIEN 0', 'NV@NV0', '1000', 'NV0', 'PASSWORD'
CREATE PROC SP_SEL_ENCRYPT_NHANVIEN 
	AS SELECT MANV, HOTEN, EMAIL, LUONG = CONVERT(VARCHAR(MAX), NHANVIEN.LUONG) FROM NHANVIEN 


CREATE PROC UPDATE_NV
	@MANV NVARCHAR(20),
	@HOTEN NVARCHAR(100),
	@EMAIL NVARCHAR(100),
	@LUONG VARCHAR(MAX),
	@TENDN NVARCHAR(100),
	@MATKHAU NVARCHAR(MAX)
AS
	UPDATE NHANVIEN SET HOTEN = @HOTEN, 
			EMAIL = @EMAIL, 
			LUONG = CAST(@LUONG AS varbinary(MAX)), 
			TENDN = @TENDN,
			MATKHAU = CAST(@MATKHAU AS varbinary(MAX)) 
	WHERE MANV = @MANV

CREATE PROC FIND_NV 
	@MANV NVARCHAR(20)
AS 
	SELECT TOP 1 MANV, HOTEN, EMAIL, LUONG  = CONVERT(VARCHAR(MAX), NHANVIEN.LUONG), TENDN 
	FROM NHANVIEN WHERE MANV = @MANV


CREATE PROC LOGIN_NV
	@MANV NVARCHAR(20),
	@PASSWORD VARCHAR(MAX)
AS SELECT TOP 1 * FROM NHANVIEN WHERE MANV = @MANV AND CAST(@PASSWORD AS varbinary(MAX)) = MATKHAU

SELECT NV_PASSWORD = CONVERT(VARCHAR(MAX), NHANVIEN.MATKHAU) FROM NHANVIEN

CREATE PROC LOGIN_SV
	@MANV NVARCHAR(20),
	@PASSWORD VARCHAR(MAX)
AS SELECT TOP 1 * FROM SINHVIEN WHERE MASV = @MANV AND CAST(@PASSWORD AS varbinary(MAX)) = MATKHAU
