CREATE DATABASE QLSV_CANHAN
USE QLSV_CANHAN
CREATE TABLE SINHVIEN
(
	MASV NVARCHAR(20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY NOT NULL
)
GO
CREATE TABLE NHANVIEN 
(
	MANV VARCHAR(20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY,
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY NOT NULL
)
GO
CREATE TABLE LOP 
(
	MALOP VARCHAR(20) PRIMARY KEY,
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20)
)
--CAU 3
--i
CREATE PROC SP_INS_ENCRYPT_SINHVIEN 	@MASV NVARCHAR(20),	@HOTEN NVARCHAR(100),	@NGAYSINH DATETIME,	@DIACHI NVARCHAR(200),	@MALOP NVARCHAR(20),	@TENDN NVARCHAR(100),	@MATKHAU VARBINARYAS 	INSERT INTO SINHVIEN(MASV, HOTEN, NGAYSINH, DIACHI, MALOP, TENDN, MATKHAU) VALUES(@MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, @MATKHAU)--CAU iiCREATE PROC SP_INS_ENCRYPT_NHANVIEN	@MANV NVARCHAR(20),	@HOTEN NVARCHAR(100),	@EMAIL DATETIME,	@LUONG VARBINARY,	@TENDN NVARCHAR(100),	@MATKHAU VARBINARY	AS	INSERT INTO NHANVIEN VALUES(@MANV, @HOTEN, @EMAIL, @LUONG, @TENDN, @MATKHAU)--CAU iiiCREATE PROC SP_SEL_ENCRYPT_NHANVIEN 	AS SELECT MANV, HOTEN, EMAIL, LUONG FROM NHANVIEN