//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAI4_CANHANH
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP
    {
        public string MALOP { get; set; }
        public string TENLOP { get; set; }
        public string MANV { get; set; }
    }
}
